homeApp/urls.py
from django.urls import path

###registering appname to hyperlink in htmls
app_name = 'homeApp'
from . import views




urlpatterns = [
    path('',views.index,name="index"),
    path("aboutus",views.aboutus,name="aboutus"),
    path("contactus",views.contactus,name="contactus"),
    path("restaurant",views.restaurant,name="restaurant"),
    path("payment",views.payment,name="payment"),
    path("homepage",views.homepage,name="homepage"),
    path("restaurant_log_in",views.restaurant,name="restaurant_log_in"),
    path("confirm_payment",views.confirm_payment,name="confirm_payment"),
    path("confirm_foodman",views.confirm_foodman,name="confirm_foodman")


    
]

khanabazaar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin/', include("adminApp.urls")),
    path('', include("homeApp.urls")),
    path('rest/', include("restApp.urls")),
    path('foodman/', include("foodmanApp.urls")),
]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restApp/urls.py
from django.urls import path

app_name = 'restApp'

from . import views



urlpatterns = [
    path('', views.index, name='index'),
    path('add_food/', views.add_food, name='add_food'),
    path('edit_food/', views.edit_food, name='edit_food'),
    path('edit_particular_food/', views.edit_particular_food, name='edit_particular_food'),
    path('update_time/', views.update_time, name='update_time'),
    path('update_logo/', views.update_logo, name='update_logo'),
    path('update_location/', views.update_location, name='update_location'),
]

restApp/models.py
from django.db import models

# Create your models here.

restApp/views.py
from django.contrib import messages
from django.shortcuts import render, redirect

from helper import sql, fetch_all
from helper.location import valid_location, buet_location
from helper.read_write_to_file import handle_uploaded_file
from helper.session import not_this_season
from helper.wrap_and_encode import get_hashed_value, wrap_with_in_single_quote
from khanabazaar.settings import STATIC_ROOT, IMAGE_PATH
from restApp.urls import app_name


def index(request):
    context = {}
    not_this_season(request, app_name)
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        password = get_hashed_value(password)
        c = sql.create_cursor()
        to_execute = "SELECT * FROM RESTAURANT WHERE EMAIL ={email} AND PASSWORD_HASH ={password}"
        # print(to_execute)

        to_execute = to_execute.format(
            email=wrap_with_in_single_quote(email),
            password=wrap_with_in_single_quote(password)
        )
        c.execute(to_execute)
        rest = c.fetchone()
        c.close()
        if rest is None:
            messages.info(request, 'Please provide correct information')
            return render(request, 'restApp/sign_in.html', context)
        else:
            id = rest[0]
            name = rest[1]
            location = rest[2]
            if not valid_location(location):
                location = buet_location

            email = rest[7]
            # password = rest[8]
            request.session['id'] = id
            request.session['user_name'] = name
            request.session['email'] = email
            request.session['location'] = location
            request.session['app_name'] = app_name
            context['user_name'] = request.session.get('user_name')
            return render(request, 'restApp/index.html', context)

    elif request.method == 'GET':
        action = request.GET.get('action')
        if action == 'logout':
            request.session.flush()
            print('log out ing')
            return render(request, 'restApp/sign_in.html', context)

        if not request.session.is_empty():
            context['user_name'] = request.session.get('user_name')
            return render(request, 'restApp/index.html', context)
        else:
            return render(request, 'restApp/sign_in.html', context)

    return render(request, 'restApp/sign_in.html', context)


def add_food(request):
    context = {}
    if not_this_season(request, app_name):
        messages.info(request, 'Please log in')
        return redirect('/rest')
    if request.method == 'POST':

        try:
            name = request.POST.get('name')
            image = request.FILES['food_image']
            price = request.POST.get('price')
            description = request.POST.get('description')
            food_id = sql.get_next_id()
            rest_id = request.session.get('id')
            Type = request.POST.get('type')
            image_id = 0
            # this are default
            available = 'N'
            offer = 0
            food_image_path = None

            conn = sql.open_connection()
            cursor = conn.cursor()
            # first add to fooditem table
            to_execute = "INSERT INTO FOOD_ITEM(ID, RESTAURANT_ID, NAME, PRICE,OFFER, AVAILIBILITY, DESCRIPTION, TYPE) " \
                         "VALUES ({id}, {rest_id}, {name},{price}, {offer}, {availibiliy}, {description}, {type} )"
            to_execute = to_execute.format(
                id=wrap_with_in_single_quote(food_id),
                rest_id=wrap_with_in_single_quote(rest_id),
                name=wrap_with_in_single_quote(name),
                price=price,
                offer=offer,
                availibiliy=wrap_with_in_single_quote(available),
                description=wrap_with_in_single_quote(description),
                type=wrap_with_in_single_quote(Type)
            )
            # print(to_execute)
            cursor.execute(to_execute)

            # now add to food item path
            if image is not None:
                image_id = sql.get_next_id()
                food_image_path = 'food' + image_id + '.jpg'
                handle_uploaded_file(image, food_image_path, STATIC_ROOT + '/img')
                handle_uploaded_file(image, food_image_path, IMAGE_PATH + '/img/')
            else:
                food_image_path = 'food' + image_id + '.jpg'

            to_execute = "INSERT INTO FOOD_ITEM_PATH(ID, IMAGE_PATH) VALUES ( {id}, {food_path})"
            to_execute = to_execute.format(
                id=wrap_with_in_single_quote(food_id),
                food_path=wrap_with_in_single_quote(food_image_path)
            )
            cursor.execute(to_execute)
            cursor.close()
            conn.commit()
            messages.info(request, 'Successfully added Food')

        except Exception as e:
            print(e)
            print("something is wrong in adding food")
            print(e)
            messages.info(request, 'some error occured!')
            try:
                conn.rollback()
            except:
                pass
        finally:
            try:
                conn.close()
            except:
                pass

    return render(request, 'restApp/add_food.html', context)


def edit_food(request):
    context = {}
    if not_this_season(request, app_name):
        messages.info(request, 'Please log in')
        return redirect('/rest')
    if request.method == 'GET':

        if not request.session.is_empty():
            rest_id = request.session.get('id')
            context['foods'] = fetch_all.food_item_all(rest_id)
            return render(request, 'restApp/edit_food.html', context)

    return render(request, 'restApp/edit_food.html', context)


def edit_particular_food(request):
    context = {}
    if not_this_season(request, app_name):
        messages.info(request, 'Please log in')
        return redirect('/rest')
    rest_id = request.session.get('id')
    if request.method == 'GET':
        # print(request.GET)
        food_id = request.GET.get('food_id')
        if food_id is not None:
            # print('one is ', food_id)
            context = fetch_all.food_item(food_id=food_id, rest_id=rest_id)
            return render(request, 'restApp/edit_particular_food.html', context)
        else:
            return redirect('/rest/edit_food')
    if request.method == 'POST':
        # print(request.POST)
        try:
            food_id = request.POST.get('food_id')
            name = request.POST.get('name')
            price = request.POST.get('price')
            offer = request.POST.get('offer')
            availibility = request.POST.get('availibility')
            description = request.POST.get('description')
            Type = request.POST.get('type')

            to_execute = "UPDATE FOOD_ITEM SET NAME={name},PRICE={price},OFFER={offer},AVAILIBILITY = {availibility}, DESCRIPTION={description},TYPE={type} " \
                         "WHERE ID = {id} and RESTAURANT_ID ={rest_id}"
            to_execute = to_execute.format(
                name=wrap_with_in_single_quote(name),
                price=price,
                offer=offer,
                availibility=wrap_with_in_single_quote(availibility),
                description=wrap_with_in_single_quote(description),
                type=wrap_with_in_single_quote(Type),
                id=wrap_with_in_single_quote(food_id),
                rest_id=wrap_with_in_single_quote(rest_id)
            )
            # print(to_execute)
            sql.execute(to_execute)

            rest = fetch_all.food_item(food_id, rest_id)
            context.update(rest)
            messages.info(request, "Successfully Updated")
            return render(request, "restApp/edit_particular_food.html", context)
        except Exception as e:
            print(e)
            messages.info(request, 'some error occured', )
            return redirect('/rest/edit_food')


def update_time(request):
    context = {}
    if not_this_season(request, app_name):
        messages.info(request, 'Please log in')
        return redirect('/rest')
    rest_id = request.session.get('id')
    context['hour_list'] = range(24)
    context['minute_list'] = range(0, 60, 1)
    if request.method == 'GET':
        rest = fetch_all.restaurant(rest_id)
        print(rest)
        context.update(rest)
        return render(request, 'restApp/update_time.html', context)
    elif request.method == 'POST':
        open_time = request.POST.get('openTime')
        close_time = request.POST.get('closeTime')
        cursor = sql.create_cursor()
        to_execute = "UPDATE RESTAURANT SET OPEN_TIME = {open_time}, CLOSE_TIME= {close_time} WHERE ID ={id}"
        to_execute = to_execute.format(
            open_time=wrap_with_in_single_quote(open_time),
            close_time=wrap_with_in_single_quote(close_time),
            id=wrap_with_in_single_quote(rest_id)
        )
        sql.execute(to_execute)
        rest = fetch_all.restaurant(rest_id)
        # print(rest)
        context.update(rest)
        messages.info(request, 'Update Done !!!')
        return render(request, 'restApp/update_time.html', context)


def update_logo(request):
    context = {}
    if not_this_season(request, app_name):
        messages.info(request, 'Please log in')
        return redirect('/rest')
    rest_id = request.session.get('id')
    if request.method == 'GET':
        rest = fetch_all.restaurant(rest_id)
        context.update(rest)
        return render(request, 'restApp/update_logo.html', context)
    elif request.method == 'POST':
        try:
            logo = request.FILES.get('restaurantLogo')
            if logo is not None:
                logo_path = 'rest' + rest_id + '.' + 'jpg'
                handle_uploaded_file(logo, logo_path, IMAGE_PATH + '/img/')
                handle_uploaded_file(logo, logo_path, STATIC_ROOT + '/img/')

restApp/templates/restApp/add_food.html
{% load static %}
{% static 'img' as baseURL %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>KHANABAZAAR rest</title>
    <!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <link rel="icon" type="image/png" href="{% static 'restApp/img/khanabazaar.png' %}">

    <!--build:css css/main.css-->
    <link rel="stylesheet" href="{% static 'restApp/modules/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'restApp/modules/bootstrap-social/bootstrap-social.css' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'restApp/modules/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'restApp/css/styles.css' %}">
    <!--flickity-->
    <link rel="stylesheet" href="https://unpkg.com/flickity@2/dist/flickity.min.css">
    <!--endbuild-->
</head>

<body class="background" data-spy="scroll">
<nav class="navbar navbar-dark bg-dark navbar-expand-sm fixed-top">
    <div class="container">
        <!--responsive navbar-->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'restApp:index' %}"><img src="{% static 'restApp/img/khanabazaar.png' %}"
                                                                      alt="LOGO" width="41" height="30">
            <span>KHANABAZAAR</span></a>
        <div class="collapse navbar-collapse" id="navbar">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active" hidden><a class="nav-link" href="#"><span class="fa fa-home fa-lg"></span> Home</a>
                </li>
                <li class="nav-item" hidden><a class="nav-link" href="#"><span class="fa fa-info fa-lg"></span> AboutUs</a>
                </li>
                <li class="nav-item" hidden><a class="nav-link" href="#"><span class="fa fa-list fa-lg"></span> Menu</a></li>
                <li class="nav-item" hidden><a class="nav-link" href="#"><span class="fa fa-address-card fa-lg"></span> Contact</a>
                </li>

                {#                    <li class="nav-item"><a class="nav-link" role="button" id="login"><span class="fa fa-sign-in"></span> Sign In</a></li>#}
{#                <li class="nav-item"><a class="nav-link" id="user_name"><i class="fa fa-user"></i> {{ user_name }}</a>#}
{#                </li>#}

                <li class="nav-item"><a class="nav-link" role="button" id="logout" type="submit"
                                        href="{% url 'restApp:index' %}?action=logout"><span
                        class="fa fa-sign-out"></span> Log out </a></li>

            </ul>
            <!--modal button-->
        </div>


    </div>

</nav>


<header class="jumbotron">
    <div class="container header-content">
        <div class="row">
            <div class="col-12 col-sm-6">
                <div class="title">
                    <h1 class="ml-0">🅺🅷🅰🅽🅰🅱🅰🆉🅰🅰🆁</h1>
                </div>
                <p>We take inspiration from the World's best cuisines, and create a unique fusion experience. Our
                    lipsmacking creations will tickle your culinary senses!</p>
            </div>
            <div class="col-12 col-sm-3 mt-0">
                <img src="{% static 'restApp/img/khanabazaar.png' %}" class="img-fluid">
            </div>
            <div class="col-12 col-sm-3 align-self-center">
                <!--adding tooltip
                <a class="btn btn-block btn-warning btn-sm" href="#reservation" role="button"
                data-toggle="tooltip" data-html="true"
                title="or call at<br> +01710100921" data-placement="bottom">Reserve Table</a>-->
                <!--<a class="btn btn-block btn-warning btn-sm" href="#reservation" role="button" id="reservetable" >Reserve Table</a>-->


            </div>
        </div>
    </div>
</header>

<div class="container background">
    <h1 class="d-flex justify-content-center">Add a New Food item</h1>
    <form action="." method="POST" class="offset-1" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row form-group">
            <label for="name" class="col-md-2 col-form-label bg-info d-flex justify-content-center">Name : </label>
            <div>
                <input type="text" class="form-control" id="name" name="name" placeholder="name">
            </div>
        </div>


        <div class="row form-group">
            <label for="food_image" class="col-md-2 col-form-label bg-info d-flex justify-content-center">Food
                Image : </label>
            <div>
                <input type="file" class="form-control" id="food_image"
                       name="food_image" placeholder="choose image" accept="image/png, image/jpg, image/jpeg"
                       enctype="multipart/form-data">
            </div>

        </div>


        <div class="row form-group">
            <label for="price" class="col-md-2 col-form-label bg-info d-flex justify-content-center">Price
                : </label>
            <div>
                <input type="text" class="form-control" id="price" name="price" placeholder="price">
            </div>
        </div>

        <div class="row form-group">
            <label for="type" class="col-md-2 col-form-label bg-info d-flex justify-content-center">Type
                : </label>
            <div>
                <input type="text" class="form-control" id="type" name="type" placeholder="burger">
            </div>
        </div>

        <div class="row form-group">
            <label for="description" class="col-md-2 col-form-label bg-info d-flex justify-content-center">Description
                : </label>
            <div>
                <input type="text" class="form-control" id="description" name="description" placeholder="description">
            </div>
        </div>

        <div class="form-group row">
            <div class="offset-md-2 col-md-10">
                <input type="submit" class="btn btn-primary" placeholder="submit">

            </div>
        </div>


    </form>
    <script>
        var m = '';
        {% for message in messages %}
            m = m + '{{ message }}';
        {% endfor %}
        if (m != '')
            alert(m);
    </script>
</div>

<div class="row restaurant-search-row-header">

</div>
<!--restaurant 1st row-->


<footer class="footer">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-4 col-sm-2">
                <h5>Links</h5>
                <ul class="list-unstyled">
                    <li><a href="#">Home</a></li>
                    <li><a href="#">About</a></li>
                    <li><a href="#">Menu</a></li>
                    <li><a href="#">Contact</a></li>
                </ul>
            </div>
            <div class="col-7 col-sm-5">
                <h5>Our Address</h5>
                <address>
                    121, Clear Water Bay Road<br>
                    Clear Water Bay, Kowloon<br>
                    HONG KONG<br>
                    <i class="fa fa-phone fa-lg"></i> Tel.: +852 1234 5678<br>
                    <i class="fa fa-fax fa-lg"></i> Fax: +852 8765 4321<br>
                    <i class="fa fa-envelope fa-lg"></i> Email: <a
                        href="mailto:confusion@food.net">confusion@food.net</a>
                </address>
            </div>
            <!--col aligning vertically center-->
            <div class="col-12 col-sm-4 align-self-center">
                <div>
                    <a class="btn btn-social-icon btn-google" href="http://google.com/+"><i
                            class="fa fa-google fa-lg"></i> Google+</a>
                    <a class="btn btn-social-icon btn-facebook" href="http://www.facebook.com/profile.php?id="><i
                            class="fa fa-facebook fa-lg"></i> Facebook</a>
                    <a class="btn btn-social-icon btn-linkedin" href="http://www.linkedin.com/in/"><i
                            class="fa fa-linkedin fa-lg"></i> LinkedIn</a>
                    <a class="btn btn-social-icon btn-twitter" href="http://twitter.com/"><i
                            class="fa fa-twitter fa-lg"></i> Twitter</a>
                    <a class="btn btn-social-icon btn-google" href="http://youtube.com/"><i
                            class="fa fa-youtube fa-lg"></i> YouTube</a>
                    <a class="btn btn-social-icon" href="mailto:"><i class="fa fa-envelope-o fa-lg"></i> Mail</a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-auto">
                <p>© Copyright 2020 KHANABAZAAR</p>
            </div>
        </div>
    </div>
</footer>
<!-- jQuery first, then Popper.js, then Bootstrap JS. -->
<!--build:js js/main.js-->
<script src="{% static 'restApp/modules/jquery/dist/jquery.slim.min.js' %}"></script>
<script src="{% static 'restApp/modules/popper.js/dist/umd/popper.min.js' %}"></script>
<script src="{% static 'restApp/modules/bootstrap/dist/js/bootstrap.min.js' %}"></script>
{#<script src="{% static 'restApp/js/scripts.js' %}"></script>#}
{#<script src="{% static 'restApp/js/form.js' %}"></script>#}
<script src="https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js"></script>
<!--endbuild-->

<!--tootip function
<script>
   $(function () {
       $('[data-toggle="tooltip"]').tooltip()
     })
</script>-->

</body>


</html>

restApp/templates/restApp/index.html
{% load static %}
{% static 'img' as baseURL %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>KHANABAZAAR rest</title>
    <!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <link rel="icon" type="image/png" href="{% static 'restApp/img/khanabazaar.png' %}">

    <!--build:css css/main.css-->
    <link rel="stylesheet" href="{% static 'restApp/modules/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'restApp/modules/bootstrap-social/bootstrap-social.css' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'restApp/modules/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'restApp/css/styles.css' %}">
    <!--flickity-->
    <link rel="stylesheet" href="https://unpkg.com/flickity@2/dist/flickity.min.css">
    <!--endbuild-->
</head>

<body class="background" data-spy="scroll">
<nav class="navbar navbar-dark bg-dark navbar-expand-sm fixed-top">
    <div class="container">
        <!--responsive navbar-->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="#"><img src="{% static 'restApp/img/khanabazaar.png' %}" alt="LOGO" width="41"
                                              height="30">
            <span>KHANABAZAAR</span></a>
        <div class="collapse navbar-collapse" id="navbar">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active" hidden><a class="nav-link" href="#"><span class="fa fa-home fa-lg"></span> Home</a>
                </li>
                <li class="nav-item" hidden><a class="nav-link" href="#"><span class="fa fa-info fa-lg"></span> AboutUs</a>
                </li>
                <li class="nav-item" hidden><a class="nav-link" href="#"><span class="fa fa-list fa-lg"></span> Menu</a></li>
                <li class="nav-item" hidden><a class="nav-link" href="#"><span class="fa fa-address-card fa-lg"></span> Contact</a>
                </li>

                {#                    <li class="nav-item"><a class="nav-link" role="button" id="login"><span class="fa fa-sign-in"></span> Sign In</a></li>#}
                <li class="nav-item"><a class="nav-link" id="user_name"><i class="fa fa-user"></i> {{ user_name }}</a>
                </li>

                <li class="nav-item"><a class="nav-link" role="button" id="logout" type="submit"
                                        href="{% url 'restApp:index' %}?action=logout"><span
                        class="fa fa-sign-out"></span> Log out </a></li>

            </ul>
            <!--modal button-->
        </div>


    </div>

</nav>


<header class="jumbotron">
    <div class="container header-content">
        <div class="row">
            <div class="col-12 col-sm-6">
                <div class="title">
                    <h1 class="ml-0">🅺🅷🅰🅽🅰🅱🅰🆉🅰🅰🆁</h1>
                </div>
                <p>We take inspiration from the World's best cuisines, and create a unique fusion experience. Our
                    lipsmacking creations will tickle your culinary senses!</p>
            </div>
            <div class="col-12 col-sm-3 mt-0">
                <img src="{% static 'restApp/img/khanabazaar.png' %}" class="img-fluid">
            </div>
            <div class="col-12 col-sm-3 align-self-center">
                <!--adding tooltip
                <a class="btn btn-block btn-warning btn-sm" href="#reservation" role="button"
                data-toggle="tooltip" data-html="true"
                title="or call at<br> +01710100921" data-placement="bottom">Reserve Table</a>-->
                <!--<a class="btn btn-block btn-warning btn-sm" href="#reservation" role="button" id="reservetable" >Reserve Table</a>-->


            </div>
        </div>
    </div>
</header>

<div class="container  text-light bg-dark background">
    <!--adding carousel-->
    <a class="btn btn-block  btn-sm bg-light" role="button" id="add_food" href="{% url 'restApp:add_food' %} ">Add
        Food</a>
    <a class="btn btn-block  btn-sm bg-light" role="button" id="edit_food" href="{% url 'restApp:edit_food' %}">Edit
        Food</a>


    <a class="btn btn-block  btn-sm bg-light" role="button" id="update_opening_closing" href="{% url 'restApp:update_time' %}">Update
        opening and closing time</a>
    <a class="btn btn-block  btn-sm bg-light" role="button" id="update_location" href="{% url 'restApp:update_location' %}">Update
        location </a>

    <a class="btn btn-block  btn-sm bg-light" role="button" id="change_logo" href="{% url 'restApp:update_logo' %} ">Change
        Logo</a>

</div>

<script>

    var m = '';
    {% for message in messages %}
        m = m + '{{ message }}';
    {% endfor %}
    if (m != '')
        alert(m);
</script>
<!--restaurant 1st row-->


<footer class="footer">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-4 col-sm-2">
                <h5>Links</h5>
                <ul class="list-unstyled">
                    <li><a href="#">Home</a></li>
                    <li><a href="#">About</a></li>
                    <li><a href="#">Menu</a></li>
                    <li><a href="#">Contact</a></li>
                </ul>
            </div>
            <div class="col-7 col-sm-5">
                <h5>Our Address</h5>
                <address>
                    121, Clear Water Bay Road<br>
                    Clear Water Bay, Kowloon<br>
                    HONG KONG<br>
                    <i class="fa fa-phone fa-lg"></i> Tel.: +852 1234 5678<br>
                    <i class="fa fa-fax fa-lg"></i> Fax: +852 8765 4321<br>
                    <i class="fa fa-envelope fa-lg"></i> Email: <a
                        href="mailto:confusion@food.net">confusion@food.net</a>
                </address>
            </div>
            <!--col aligning vertically center-->
            <div class="col-12 col-sm-4 align-self-center">
                <div>
                    <a class="btn btn-social-icon btn-google" href="http://google.com/+"><i
                            class="fa fa-google fa-lg"></i> Google+</a>
                    <a class="btn btn-social-icon btn-facebook" href="http://www.facebook.com/profile.php?id="><i
                            class="fa fa-facebook fa-lg"></i> Facebook</a>
                    <a class="btn btn-social-icon btn-linkedin" href="http://www.linkedin.com/in/"><i
                            class="fa fa-linkedin fa-lg"></i> LinkedIn</a>
                    <a class="btn btn-social-icon btn-twitter" href="http://twitter.com/"><i
                            class="fa fa-twitter fa-lg"></i> Twitter</a>
                    <a class="btn btn-social-icon btn-google" href="http://youtube.com/"><i
                            class="fa fa-youtube fa-lg"></i> YouTube</a>
                    <a class="btn btn-social-icon" href="mailto:"><i class="fa fa-envelope-o fa-lg"></i> Mail</a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-auto">
                <p>© Copyright 2020 KHANABAZAAR</p>
            </div>
        </div>
    </div>
</footer>
<!-- jQuery first, then Popper.js, then Bootstrap JS. -->
<!--build:js js/main.js-->
<script src="{% static 'restApp/modules/jquery/dist/jquery.slim.min.js' %}"></script>
<script src="{% static 'restApp/modules/popper.js/dist/umd/popper.min.js' %}"></script>
<script src="{% static 'restApp/modules/bootstrap/dist/js/bootstrap.min.js' %}"></script>
{#<script src="{% static 'restApp/js/scripts.js' %}"></script>#}
{#<script src="{% static 'restApp/js/form.js' %}"></script>#}
<script src="https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js"></script>
<!--endbuild-->

<!--tootip function
<script>
   $(function () {
       $('[data-toggle="tooltip"]').tooltip()
     })
</script>-->

</body>


</html>