adminApp/urls.py
app_name = 'adminApp'
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('add_restaurant', views.add_restaurant, name='add_restaurant'),
    path('create_promo', views.create_promo, name='create_promo'),
    path('add_foodman', views.add_food_man, name='add_foodman'),
    path('edit_restaurant', views.edit_restaurant, name='edit_restaurant'),
    path('offer_promo/', views.offer_promo, name='offer_promo'),
    path('suspend_customer/', views.suspend_customer, name='suspend_customer'),
    path('suspend_foodman/', views.suspend_foodman, name='suspend_foodman')

]

homeApp/urls.py
from django.urls import path

###registering appname to hyperlink in htmls
app_name = 'homeApp'
from . import views




urlpatterns = [
    path('',views.index,name="index"),
    path("aboutus",views.aboutus,name="aboutus"),
    path("contactus",views.contactus,name="contactus"),
    path("restaurant",views.restaurant,name="restaurant"),
    path("payment",views.payment,name="payment"),
    path("homepage",views.homepage,name="homepage"),
    path("restaurant_log_in",views.restaurant,name="restaurant_log_in"),
    path("confirm_payment",views.confirm_payment,name="confirm_payment"),
    path("confirm_foodman",views.confirm_foodman,name="confirm_foodman")


    
]

khanabazaar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin/', include("adminApp.urls")),
    path('', include("homeApp.urls")),
    path('rest/', include("restApp.urls")),
    path('foodman/', include("foodmanApp.urls")),
]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminApp/views.py
from shutil import copyfile

from django.contrib import messages
from django.shortcuts import render, redirect

from adminApp.urls import app_name
from helper import sql, fetch_all
from helper.promo import promo_exists
from helper.read_write_to_file import handle_uploaded_file
from helper.session import not_this_season
from helper.sql import get_next_id
from helper.wrap_and_encode import wrap_with_in_single_quote, get_hashed_value
from khanabazaar.settings import IMAGE_PATH, STATIC_ROOT, DEFAULT_IMAGE_PATH


# app_name = 'homeApp'

# Create your views here.

def index(request):
    context = {}
    not_this_season(request, app_name)
    if request.method == 'POST':
        try:
            email = request.POST.get('email')
            password = request.POST.get('password')
            password = get_hashed_value(password)
            c = sql.create_cursor()
            to_execute = "Select * From ADMIN Where EMAIL = {email} " \
                         "and PASSWORD_HASH = {password}"
            to_execute = to_execute.format(
                email=wrap_with_in_single_quote(email),
                password=wrap_with_in_single_quote(password)
            )
            c.execute(to_execute)
            admin = c.fetchone()

            if admin is None:
                messages.info(request, "Incorrect credentials")
                return render(request, 'adminApp/sign_in.html', context)
            else:
                id = admin[0]
                last_name = admin[1]
                first_name = admin[2]
                request.session['id'] = id
                request.session['last_name'] = last_name
                request.session['first_name'] = first_name
                request.session['email'] = email
                request.session['app_name'] = app_name
                request.session['user_name'] = last_name
                context['user_name'] = last_name
                return render(request, 'adminApp/index.html', context)
        except Exception as e:
            print(e)
            messages.info(request, "Some unknown error occured!")
            return render(request, 'adminApp/index.html', context)
        finally:
            c.close()
            pass

    elif request.method == 'GET':
        try:
            action = request.GET.get('action')
            if action == 'logout':
                if not request.session.is_empty():
                    request.session.flush()
                    messages.info(request, 'You have successfully Log out!')
                    return render(request, 'adminApp/sign_in.html', context)

            if not request.session.is_empty():
                context['user_name'] = request.session.get('last_name')
                return render(request, 'adminApp/index.html', context)
            else:
                return render(request, 'adminApp/sign_in.html', context)
        except Exception as e:
            print(e)
            messages.info(request, "Some unknown error occured!")
            return render(request, 'adminApp/sign_in.html', context)


def add_restaurant(request):
    context = {}

    if not_this_season(request, app_name):
        messages.info(request, 'YOU ARE NOT LOGGED IN ')
        return redirect('/admin')
    if request.method == 'POST':
        try:
            name = request.POST.get('name')
            location = request.POST.get('location')
            logo = request.FILES.get('restaurantLogo')
            email = request.POST.get('email')
            open_time = request.POST.get('openTime')
            close_time = request.POST.get('closeTime')
            password1 = request.POST.get('password1')
            password1 = get_hashed_value(password1)
            password2 = request.POST.get('password2')
            id = get_next_id()
            logo_path = 'rest' + id + '.' + 'jpg'
            # print(type(logo))
            # print(logo)
            if logo is not None:
                handle_uploaded_file(logo, logo_path, IMAGE_PATH + '/img/')
                handle_uploaded_file(logo, logo_path, STATIC_ROOT + '/img/')
                # collectstatic()
            else:
                try:  # we will use rest0 as a default restaurant pic
                    image_path = DEFAULT_IMAGE_PATH + 'rest0.jpg'
                    copyfile(image_path, IMAGE_PATH + '/img/' + logo_path)
                    copyfile(image_path, STATIC_ROOT + '/img/' + logo_path)
                except Exception as e:
                    print(e)
                    pass
                finally:
                    pass

            to_execute = "INSERT INTO RESTAURANT(ID,NAME,LOCATION,LOGO_PATH,RATING,OPEN_TIME,CLOSE_TIME,EMAIL,PASSWORD_HASH)" \
                         "VALUES({id}, {name}, {location}, {logo_path}, {rating}, {open_time}, {close_time}, {email}, " \
                         "{password_hash}) "
            to_execute = to_execute.format(
                id=wrap_with_in_single_quote(id),
                name=wrap_with_in_single_quote(name),
                location=wrap_with_in_single_quote(location),
                logo_path=wrap_with_in_single_quote(logo_path),
                rating=5.00,
                open_time=wrap_with_in_single_quote(open_time),
                close_time=wrap_with_in_single_quote(close_time),
                email=wrap_with_in_single_quote(email),
                password_hash=wrap_with_in_single_quote(password1)
            )
            # print(wrap_with_in_single_quote(email))
            # print(to_execute)
            sql.execute(to_execute)

            # Now adding into relation manages
            to_execute = "INSERT INTO MANAGES(RESTAURANT_ID, ADMIN_ID) " \
                         "VALUES({restaurant_ID}, {admin_ID})"
            to_execute = to_execute.format(
                restaurant_ID=wrap_with_in_single_quote(id),
                admin_ID=wrap_with_in_single_quote(request.session.get('id')))
            # print(to_execute)
            sql.execute(to_execute)
            messages.info(request, 'Restaurant has been successfully added')
            return redirect('/admin/add_restaurant')
        except Exception as e:
            print(e)
            messages.info(request, 'restaurant was not added')
            return redirect('/admin/add_restaurant')
        finally:
            pass
    context.update(request.session)
    return render(request, 'adminApp/add_restaurant.html', context)


def add_food_man(request):
    """
    handles the view of add foodman
    :param request:
    :return:
    """
    context = {}
    if not_this_season(request, app_name):
        messages.info(request, 'Please sign in first')
        return redirect('/admin')
    if request.method == 'POST':
        try:
            name = request.POST.get('name')
            phone1 = request.POST.get('phone1')
            email = request.POST.get('email')
            password1 = request.POST.get('password1')
            password1 = get_hashed_value(password1)
            password2 = request.POST.get('password2')
            password2 = get_hashed_value(password2)
            vehicle_type = request.POST.get('vehicle_type')
            reg_no = request.POST.get('reg_no')
            salary = request.POST.get('salary')
            duration = request.POST.get('duration')  # in months
            init_rating = request.POST.get('init_rating')
            if init_rating is None:
                init_rating = 4.00
            profile_img = request.FILES.get('profile_img')
            profile_img_path = None
            foodman_id = get_next_id()
            profile_img_path = 'foodman' + foodman_id + '.' + 'jpg'
            if profile_img is not None:
                handle_uploaded_file(profile_img, profile_img_path, IMAGE_PATH + '/img/')
                handle_uploaded_file(profile_img, profile_img_path, STATIC_ROOT + '/img/')
            else:
                try:
                    image_path = DEFAULT_IMAGE_PATH + 'foodman0.jpg'
                    copyfile(image_path, IMAGE_PATH + '/img/' + profile_img_path)
                    copyfile(image_path, STATIC_ROOT + '/img/' + profile_img_path)
                except:
                    pass

            cursor = sql.create_cursor()
            admin_id = request.session.get('id')
            cursor.callproc('ADD_FOODMAN', [admin_id, foodman_id, name, email, password1, phone1,
                                            init_rating, profile_img_path, reg_no, vehicle_type, salary, duration])
            messages.info(request, "adding of foodman was successfull")

        except Exception as e:
            print("Something is not right. And why rollback is not working.")
            print(e)
            messages.info(request, "adding of foodman was unsuccessfull")

        finally:
            try:
                cursor.close()
            except:
                pass
    context.update(request.session)
    return render(request, 'adminApp/add_foodman.html', context)


def create_promo(request):
    """
    handles the view off adding promo
    :param request:
    :return:
    """
    context = {}
    # for r in request.session.items():
    #     print(r)
    if not_this_season(request, app_name):
        messages.info(request, "Something went wrong. Please Log in again")
        return redirect('/admin')
    if request.method == 'POST':
        name = request.POST.get('name')
        if promo_exists(name):
            messages.info(request, 'The promo exists')
        else:
            try:
                percent = request.POST.get('percent')
                fixed_amount = request.POST.get('fixed_amount')
                promo_limit = request.POST.get('promo_limit')
                min_order_value = request.POST.get('min_order_value')
                max_discount_amount = request.POST.get('max_discount_amount')
                promo_id = sql.get_next_id()
                to_execute = "INSERT INTO PROMO(ID, NAME, PERCENT, FIXED_AMOUNT, PROMO_LIMIT, MIN_ORDER_VALUE, " \

adminApp/templates/adminApp/contactus.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <title>Ristorante Con Fusion: About Us</title>
    <!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    
     <!--build:css css/main.css-->
     <link rel="stylesheet" href="{% static 'homeApp/modules/font-awesome/css/font-awesome.min.css' %}">
     <link rel="stylesheet" href="{% static 'homeApp/modules/bootstrap-social/bootstrap-social.css' %}">
     <!-- Bootstrap CSS -->
     <link rel="stylesheet" href="{% static 'homeApp/modules/bootstrap/dist/css/bootstrap.min.css' %}">
     <link rel="stylesheet" href="{% static 'homeApp/css/styles.css' %}">
     <!--endbuild-->
</head>

<body class="background">
    <nav class="navbar navbar-dark bg-dark navbar-expand-sm fixed-top">
        <div class="container">
            <!--responsive navbar-->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" href="#"><img src="{% static 'homeApp/img/khanabazaar.png' %}" alt="LOGO" width="41" height="30">
                <span>KHANABAZAAR</span></a>
            <div class="collapse navbar-collapse" id="navbar">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active"><a class="nav-link" href="#"><span class="fa fa-home fa-lg"></span> Home</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'homeApp:aboutus' %}"><span class="fa fa-info fa-lg"></span> AboutUs</a></li>
                    <li class="nav-item"><a class="nav-link" href="#"><span class="fa fa-list fa-lg"></span> Menu</a></li>
                    <li class="nav-item  active"><a class="nav-link" href="{% url 'homeApp:contactus' %}"><span class="fa fa-address-card fa-lg"></span> Contact</a></li>
                    <li class="nav-item"><a class="nav-link" role="button" id="login"><span class="fa fa-sign-in"></span> Sign In</a></li>
                </ul>
                <!--modal button-->
            </div>
           

        </div>

    </nav>

    <header class="jumbotron">
        <div class="container">
            <div class="row row-header">
                <div class="col-12 col-sm-2 align-self-center">
                    <img src="{% static 'homeApp/img/khanabazaar.png' %}" class="img-fluid">
                </div>
                <div class="col-12 col-sm-9 offset-sm-1">
                    <h1>Ristorante con Fusion</h1>
                    <p>We take inspiration from the World's best cuisines, and create a unique fusion experience. Our lipsmacking creations will tickle your culinary senses!</p>
                </div>
                </div>
            </div>
        </div>
    </header>

    <div class="container">
        <div class="row">
            <ol class="col-12 breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'homeApp:index' %}">Home</a></li>
                <li class="breadcrumb-item active"><a href="{% url 'homeApp:contactus' %}">Contact Us</a></li>
            </ol>
            <div class="col-12">
               <h3>Contact Us</h3>
               <hr>
            </div>
        </div>

        <div class="row row-content">
           <div class="col-12">
              <h3>Location Information</h3>
           </div>
            <div class="col-12 col-sm-4 offset-sm-1">
                   <h5>Our Address</h5>
                    <address style="font-size: 100%">
		              121, Clear Water Bay Road<br>
		              Clear Water Bay, Kowloon<br>
		              HONG KONG<br>
		              <i class="fa fa-phone"></i>: +852 1234 5678<br>
		              <i class="fa fa-fax"></i>: +852 8765 4321<br>
		              <i class="fa fa-envelope"></i>:
                        <a href="mailto:confusion@food.net">confusion@food.net</a>
		           </address>
            </div>
            <div class="col-12 col-sm-6 offset-sm-1">
                <h5>Map of our Location</h5>
            </div>
            <div class="col-12 col-sm-11 offset-sm-1">
                <div class="btn-group" role="group">
                    <a role="button" class="btn btn-primary" href="tel+81346356231"><i class="fa fa-phone"></i> Call</a>
                    <a role="button" class="btn btn-info"><i class="fa fa-skype"></i> Skype</a>
                    <a role="button" class="btn btn-success" href="mailto:Saiful@isslam.net"><i class="fa fa-envelope-o"></i> E-mail</a>

                </div>
            </div>
        </div>

        <div class="row row-content">
           <div class="col-12">
              <h3>Send us your Feedback</h3>
           </div>
            <div class="col-12 col-md-9">
                <form>
                    <div class="form-group row">
                        <label for="firstname" class="col-md-2 col-form-label form_pad">First Name</label>
                        <div class="col-md-10">
                            <input type="text" class="form-control form_pad" id="firstname" name="firstname" placeholder="First Name">
                        </div>
                        <label for="lastname" class="col-md-2 col-form-label form_pad">Last Name</label>
                        <div class="col-md-10">
                            <input type="text" class="form-control form_pad" id="lastname" name="firstname" placeholder="Last Name">
                        </div>
                    </div>
                    <!--tel,email row-->
                    <div class="form-group row">
                        <label for="telno" class="col-12 col-md-2 col-form-label">Contact Tel.</label>
                        <div class="col-5 col-md-3">
                            <input type="tel" class="form-control" id="areacode" name="areacode" placeholder="Area Code">
                        </div>
                        <div class="col-7 col-md-7">
                            <input type="tel" class="form-control" id="telno" name="telno" placeholder="Tel No.">
                        </div>
                        <label for="email" class="col-md-2 col-form-label form_pad">E-mail</label>
                        <div class="col-md-10 form_pad">
                            <input type="mail" class="form-control" id="email" name="email" placeholder="E-mail">
                        </div>
                    </div>
                    <!--checkbox row-->
                    <div class="form-group row">
                        <div class="col-md-6 offset-md-2">
                            <div class="form-check">
                                <input type="checkbox" class="form-check-input" name="approve" id="approve" value="">
                                <label for="approve" class="form-check-label">
                                    <strong>May we contact you?</strong>
                                </label>
                            </div>
                        </div>
                        <div class="col-md-3 offset-md-1">
                            <select>
                                <option>E-mail</option>
                                <option>TelNo.</option>
                            </select>
                        </div>
                    </div>
                    <!--feedback row-->
                    <div class="form-group row">
                        <label for="feedback" class="col-md-2 col-form-label ">Your Feedback</label>
                        <div class="col-md-10 form_pad">
                            <textarea class="form-control " id="feedback" name="feedback" rows="10" ></textarea>
                        </div>
                    </div>
                    <!--submit-->
                    <div class="form-group row">
                        <div class="col-12 col-md-6 offset-md-2">
                            <button class="btn btn-outline-dark" type="submit">Give Your Feedback</button>
                        </div>

                    </div>

                    </div>
                </form>
            </div>
             <div class="col-12 col-md">
            </div>
       </div>

    </div>

    <footer class="footer">
        <div class="container">
            <div class="row">             
                <div class="col-4 offset-1 col-sm-2">
                    <h5>Links</h5>
                    <ul class="list-unstyled">
                        <li><a href="#">Home</a></li>
                        <li><a href="#">About</a></li>
                        <li><a href="#">Menu</a></li>
                        <li><a href="#">Contact</a></li>
                    </ul>
                </div>
                <div class="col-7 col-sm-5">
                    <h5>Our Address</h5>
                    <address>
		              121, Clear Water Bay Road<br>
		              Clear Water Bay, Kowloon<br>
		              HONG KONG<br>
                      <i class="fa fa-phone fa-lg"></i>: +852 1234 5678<br>
                      <i class="fa fa-fax fa-lg"></i>: +852 8765 4321<br>
                      <i class="fa fa-envelope fa-lg"></i>: 
                      <a href="mailto:confusion@food.net">confusion@food.net</a>
		           </address>
                </div>
                <div class="col-12 col-sm-4 align-self-center">
                    <div class="text-center">
                        <a class="btn btn-social-icon btn-google" href="http://google.com/+"><i class="fa fa-google-plus"></i></a>
                        <a class="btn btn-social-icon btn-facebook" href="http://www.facebook.com/profile.php?id="><i class="fa fa-facebook"></i></a>
                        <a class="btn btn-social-icon btn-linkedin" href="http://www.linkedin.com/in/"><i class="fa fa-linkedin"></i></a>
                        <a class="btn btn-social-icon btn-twitter" href="http://twitter.com/"><i class="fa fa-twitter"></i></a>
                        <a class="btn btn-social-icon btn-google" href="http://youtube.com/"><i class="fa fa-youtube"></i></a>
                        <a class="btn btn-social-icon" href="mailto:"><i class="fa fa-envelope-o"></i></a>
                    </div>
                </div>
           </div>
           <div class="row justify-content-center">             
                <div class="col-auto">
                    <p>© Copyright 2018 Ristorante Con Fusion</p>
                </div>
           </div>
        </div>
    </footer>
     <!--build:js js/main.js-->
     <script src="{% static 'homeApp/modules/jquery/dist/jquery.slim.min.js' %}"></script>
     <script src="{% static 'homeApp/modules/popper.js/dist/umd/popper.min.js' %}"></script>
     <script src="{% static 'homeApp/modules/bootstrap/dist/js/bootstrap.min.js' %}"></script>
     <script src="{% static 'homeApp/js/scripts.js' %}"></script>
     <script src="{% static 'homeApp/js/form.js' %}"></script>
     <!--endbuild-->
</body>

</html>

adminApp/templates/adminApp/index.html
{% load static %}
{% static 'img' as baseURL %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>KHANABAZAAR admin</title>
    <!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <link rel="icon" type="image/png" href="{% static 'adminApp/img/khanabazaar.png' %}">

    <!--build:css css/main.css-->
    <link rel="stylesheet" href="{% static 'adminApp/modules/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminApp/modules/bootstrap-social/bootstrap-social.css' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'adminApp/modules/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminApp/css/styles.css' %}">
    <!--flickity-->
    <link rel="text/stylesheet" href="https://unpkg.com/flickity@2/dist/flickity.min.css">
    <!--endbuild-->
</head>

<body class="background" data-spy="scroll">
<nav class="navbar navbar-dark bg-dark navbar-expand-sm fixed-top">
    <div class="container">
        <!--responsive navbar-->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="#"><img src="{% static 'adminApp/img/khanabazaar.png' %}" alt="LOGO" width="41"
                                              height="30">
            <span>KHANABAZAAR</span></a>
        <div class="collapse navbar-collapse" id="navbar">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active" hidden><a class="nav-link" href="#"><span class="fa fa-home fa-lg"></span> Home</a>
                </li>
                <li class="nav-item" hidden><a class="nav-link" href="#"><span class="fa fa-info fa-lg"></span> AboutUs</a>
                </li>
                <li class="nav-item" hidden><a class="nav-link" href="#"><span class="fa fa-list fa-lg"></span> Menu</a></li>
                <li class="nav-item" hidden><a class="nav-link" href="#"><span class="fa fa-address-card fa-lg"></span> Contact</a>
                </li>

                {#                    <li class="nav-item"><a class="nav-link" role="button" id="login"><span class="fa fa-sign-in"></span> Sign In</a></li>#}
                <li class="nav-item"><a class="nav-link" id="user_name"><i class="fa fa-user"></i> {{ user_name }}</a>
                </li>

                <li class="nav-item"><a class="nav-link" role="button" id="logout" type="submit"
                                        href="{% url 'adminApp:index' %}?action=logout"><span
                        class="fa fa-sign-out"></span> Log out </a></li>

            </ul>
            <!--modal button-->
        </div>


    </div>

</nav>


<header class="jumbotron">
    <div class="container header-content">
        <div class="row">
            <div class="col-12 col-sm-6">
                <div class="title">
                    <h1 class="ml-0">🅺🅷🅰🅽🅰🅱🅰🆉🅰🅰🆁</h1>
                </div>
                <p>We take inspiration from the World's best cuisines, and create a unique fusion experience. Our
                    lipsmacking creations will tickle your culinary senses!</p>
            </div>
            <div class="col-12 col-sm-3 mt-0">
                <img src="{% static 'adminApp/img/khanabazaar.png' %}" class="img-fluid">
            </div>
            <div class="col-12 col-sm-3 align-self-center">
                <!--adding tooltip
                <a class="btn btn-block btn-warning btn-sm" href="#reservation" role="button"
                data-toggle="tooltip" data-html="true"
                title="or call at<br> +01710100921" data-placement="bottom">Reserve Table</a>-->
                <!--<a class="btn btn-block btn-warning btn-sm" href="#reservation" role="button" id="reservetable" >Reserve Table</a>-->


            </div>
        </div>
    </div>
</header>

<div class="container  text-light bg-dark background">
    <!--adding carousel-->
    <a class="btn btn-block  btn-sm bg-white" role="button" id="add_restaurant" href="{% url 'adminApp:add_restaurant' %} ">Add
        Restaurant</a>
    <a class="btn btn-block  btn-sm d-none" role="button" id="edit_restaurant"
       href="{% url 'adminApp:edit_restaurant' %}">Edit Restaurant</a>
    <div>
        <a class="btn btn-block  btn-sm bg-white" role="button" id="create_promo" href="{% url 'adminApp:create_promo' %}">Create
            Promo</a>
    </div>

    <a class="btn btn-block  btn-sm bg-white" role="button" id="offerPromo" href="{% url 'adminApp:offer_promo' %}">Offer Promo
        to Customer</a>
    <a class="btn btn-block  btn-sm bg-white" role="button" id="suspendCustomer" href="{% url 'adminApp:suspend_customer' %}">Suspend
        Customer</a>
    <a class="btn btn-block  btn-sm bg-white" role="button" id="addFoodMan" href="{% url 'adminApp:add_foodman' %}">Add
        FoodMan</a>
    <a class="btn btn-block  btn-sm bg-white" role="button" id="remove_foodman" href="{% url 'adminApp:suspend_foodman' %}">Suspend
        FoodMan</a>
    <script>
        var m = '';
        {% for message in messages %}
            m = m + '{{ message }}';
        {% endfor %}
        if (m != '')
            alert(m);
    </script>

</div>


<!--restaurant 1st row-->


<footer class="footer">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-4 col-sm-2">
                <h5>Links</h5>
                <ul class="list-unstyled">
                    <li><a href="#">Home</a></li>
                    <li><a href="#">About</a></li>
                    <li><a href="#">Menu</a></li>
                    <li><a href="#">Contact</a></li>
                </ul>
            </div>
            <div class="col-7 col-sm-5">
                <h5>Our Address</h5>
                <address>
                    121, Clear Water Bay Road<br>
                    Clear Water Bay, Kowloon<br>
                    HONG KONG<br>
                    <i class="fa fa-phone fa-lg"></i> Tel.: +852 1234 5678<br>
                    <i class="fa fa-fax fa-lg"></i> Fax: +852 8765 4321<br>
                    <i class="fa fa-envelope fa-lg"></i> Email: <a
                        href="mailto:confusion@food.net">confusion@food.net</a>
                </address>
            </div>
            <!--col aligning vertically center-->
            <div class="col-12 col-sm-4 align-self-center">
                <div>
                    <a class="btn btn-social-icon btn-google" href="http://google.com/+"><i
                            class="fa fa-google fa-lg"></i> Google+</a>
                    <a class="btn btn-social-icon btn-facebook" href="http://www.facebook.com/profile.php?id="><i
                            class="fa fa-facebook fa-lg"></i> Facebook</a>
                    <a class="btn btn-social-icon btn-linkedin" href="http://www.linkedin.com/in/"><i
                            class="fa fa-linkedin fa-lg"></i> LinkedIn</a>
                    <a class="btn btn-social-icon btn-twitter" href="http://twitter.com/"><i
                            class="fa fa-twitter fa-lg"></i> Twitter</a>
                    <a class="btn btn-social-icon btn-google" href="http://youtube.com/"><i
                            class="fa fa-youtube fa-lg"></i> YouTube</a>
                    <a class="btn btn-social-icon" href="mailto:"><i class="fa fa-envelope-o fa-lg"></i> Mail</a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-auto">
                <p>© Copyright 2020 KHANABAZAAR</p>
            </div>
        </div>
    </div>
</footer>
<!-- jQuery first, then Popper.js, then Bootstrap JS. -->
<!--build:js js/main.js-->
<script src="{% static 'adminApp/modules/jquery/dist/jquery.slim.min.js' %}"></script>
<script src="{% static 'adminApp/modules/popper.js/dist/umd/popper.min.js' %}"></script>
<script src="{% static 'adminApp/modules/bootstrap/dist/js/bootstrap.min.js' %}"></script>
{#<script src="{% static 'adminApp/js/scripts.js' %}"></script>#}
{#<script src="{% static 'adminApp/js/form.js' %}"></script>#}
<script src="https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js"></script>
<!--endbuild-->

<!--tootip function
<script>
   $(function () {
       $('[data-toggle="tooltip"]').tooltip()
     })
</script>-->

</body>


</html>