homeApp/urls.py
from django.urls import path

###registering appname to hyperlink in htmls
app_name = 'homeApp'
from . import views




urlpatterns = [
    path('',views.index,name="index"),
    path("aboutus",views.aboutus,name="aboutus"),
    path("contactus",views.contactus,name="contactus"),
    path("restaurant",views.restaurant,name="restaurant"),
    path("payment",views.payment,name="payment"),
    path("homepage",views.homepage,name="homepage"),
    path("restaurant_log_in",views.restaurant,name="restaurant_log_in"),
    path("confirm_payment",views.confirm_payment,name="confirm_payment"),
    path("confirm_foodman",views.confirm_foodman,name="confirm_foodman")


    
]

khanabazaar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin/', include("adminApp.urls")),
    path('', include("homeApp.urls")),
    path('rest/', include("restApp.urls")),
    path('foodman/', include("foodmanApp.urls")),
]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homeApp/models.py
from django.db import models

# Create your models here.

homeApp/views.py
from datetime import datetime, timedelta

import cx_Oracle
from django.shortcuts import render, redirect
import helper.wrap_and_encode

from helper import sql
from helper.sql import get_next_id
from helper.wrap_and_encode import wrap_with_in_single_quote, get_hashed_value
from homeApp.urls import app_name
from helper.session import not_this_season

con = cx_Oracle.connect("KB", "123", "localhost/orcl")
print("Connected!")
c = con.cursor()


# Create your views here.
def index(request):
    c = con.cursor()
    c.execute('select * from RESTAURANT')
    dict_result = []
    for row in c:
        id = row[0]
        name = row[1]
        path = row[3]
        dic = {'id': id, 'name': name, 'path': path}
        dict_result.append(dic)
    list1 = []
    list2 = []
    list3 = []
    brk = int(len(dict_result) / 3)
    for i in range(len(dict_result)):
        if (int(i / brk) == 0):
            list1.append(dict_result[i])
        elif (int(i / brk) == 1):
            list2.append(dict_result[i])
        else:
            list3.append(dict_result[i])
    
    #------------checking this session-----------#
    if not_this_season(request, app_name):
        c.close()
        return render(request, 'homeApp/index.html', {'list1': list1, 'list2': list2, 'list3': list3, 'contex': 'None'})


    # -------------logout--------------#
    if request.method == 'GET':
        print('get method')
        if 'action' in request.GET:
            action = request.GET.get('action')
            if action == 'logout':
                print('action logout')
                if request.session.has_key('first_name'):
                    print('has key in session')
                    if request.session['app_name'] == app_name:
                        request.session.flush()
                        return render(request, 'homeApp/index.html',
                                  {'list1': list1, 'list2': list2, 'list3': list3, 'contex': 'None'})

                    
    if not request.session.is_empty() and request.session['app_name'] ==app_name:
        print('has session while in index')
        if 'first_name' in request.session:
            first_name = request.session['first_name']
        if 'id' in request.session:
            cust_id = request.session['id']
        command = "select * from CHOOSES WHERE CUSTOMER_ID = %s" % cust_id
        c.execute(command)
        orders = c.fetchall()
        
        order_dic=[]
        pay_id = None
        restaurant_dic = []
        for r in orders:
            order_id = r[0]
            table_name = '"' + "ORDER" + '"'
            command = "select * from {table_name} WHERE ID = %s" % order_id
            command = command.format(table_name="{}".format(table_name))
            c.execute(command)
            order = c.fetchall()
            temp_dic = None
            #-----------pay id-----------#
            command = "select * from PAYS WHERE ORDER_ID = %s" % order_id
            c.execute(command)
            pays = c.fetchall()
            
            for row in order:
                ord_id = row[0]
                ord_time = row[1]
                ord_deltime = row[2]
                ord_loc = row[3]
                temp_dic = {'order_id':ord_id,'order_time':ord_time,'delivery_time':ord_deltime,'delivery_location':ord_loc}
            for row in pays:
                pay_id = row[1]
                pay_data = {'pay_id':pay_id}
                temp_dic.update(pay_data)
                break
            command = "select * from SELECTED WHERE ORDER_ID = %s" % order_id
            c.execute(command)
            food_item = c.fetchall()
            for row in food_item:
                food_id = row[1]
                command = "select * from FOOD_ITEM WHERE ID = %s" % food_id
                c.execute(command)
                fooditem_tbl = c.fetchall()
                for fooditem in fooditem_tbl:
                    rest_id = fooditem[1]
                    command = "select * from RESTAURANT WHERE ID = %s" % rest_id
                    c.execute(command)
                    restaurant_tbl = c.fetchall()
                    for rest in restaurant_tbl:
                        restaurant_data = {'restaurant_id':rest[0],'restaurant_name':rest[1],'restaurant_location':rest[2],'restaurant_path':rest[3]}
                        temp_dic.update(restaurant_data)
                        order_dic.append(temp_dic)
                        break
                    break
                break


                   
        print(order_dic)
        print(restaurant_dic)

        c.close()
        return render(request, 'homeApp/homepage.html',
                      {'list1': list1, 'list2': list2, 'list3': list3, 'customer_name': first_name,'orders':order_dic})

    # connection.commit()
    # cursor.close()
    c.close()
    return render(request, 'homeApp/index.html', {'list1': list1, 'list2': list2, 'list3': list3, 'contex': 'None'})


# --------------------------after sign in --------------------------#
def homepage(request):
    c = con.cursor()
    c.execute('select * from RESTAURANT')
    dict_result = []
    for row in c:
        id = row[0]
        name = row[1]
        path = row[3]
        dic = {'id': id, 'name': name, 'path': path}
        dict_result.append(dic)
    list1 = []
    list2 = []
    list3 = []
    brk = int(len(dict_result) / 3)
    for i in range(len(dict_result)):
        if (int(i / brk) == 0):
            list1.append(dict_result[i])
        elif (int(i / brk) == 1):
            list2.append(dict_result[i])
        else:
            list3.append(dict_result[i])

    # connection.commit()
    # cursor.close()
    #-----------check session---------#
    if not_this_season(request, app_name):
        if request.method == 'POST':
            # ------------------sign up-------------#
            star = request.POST.get('star')
            print(star)
            print('hello world')
            firstname = request.POST.get('firstname')
            lastname = request.POST.get('lastname')
            email_log = request.POST.get('email')
            phone = request.POST.get('phone')
            password1 = request.POST.get('password')
            password1 = get_hashed_value(password1)
            password2 = request.POST.get('confirmpassword')
            address = request.POST.get('address')
            id = get_next_id()
            # print(firstname+lastname+address)
            if (firstname != None and lastname != None and email_log != None):
                to_execute = "INSERT INTO CUSTOMER(ID,LAST_NAME,FIRST_NAME,EMAIL,PASSWORD_HASH,ADDRESS)" \
                            " VALUES({id}, {lastname}, {firstname}, {email}, {password_hash}, {address}) "
                to_execute_phone = "INSERT INTO CUSTOMER_PHONE(CUSTOMER_ID,PHONE_NO)" \
                                " VALUES({id}, {phone}) "
                to_execute_phone = to_execute_phone.format(
                    id=wrap_with_in_single_quote(id),
                    phone=wrap_with_in_single_quote(phone)
                )
                to_execute = to_execute.format(
                    id=wrap_with_in_single_quote(id),
                    firstname=wrap_with_in_single_quote(firstname),
                    lastname=wrap_with_in_single_quote(lastname),
                    email=wrap_with_in_single_quote(email_log),
                    password_hash=wrap_with_in_single_quote(password1),
                    address=wrap_with_in_single_quote(address)
                )

                info = id + ' ' + firstname + ' ' + lastname + ' ' + email_log
                customer_info = info.split(' ')
                print(customer_info)

                # print(firstname+lastname+address)
                print(to_execute)
                try:
                    sql.execute(to_execute)
                    sql.execute(to_execute_phone)
                    contex = 'registered successfully'
                    return render(request, 'homeApp/index.html',
                                {'list1': list1, 'list2': list2, 'list3': list3, 'contex': contex})

                except:
                    print("Something is not right. And why rollback is not working.")
                    sql.rollback()
                    # messages.info(request, "adding of foodman was unsuccessfull")
                    return render(request, 'homeApp/index.html', {'list1': list1, 'list2': list2, 'list3': list3,
                                                                'contex': 'something went wrong.try again'})

                finally:
                    c.close()
                    sql.commit()

                # return render(request, 'homeApp/homepage.html',{'list1':list1,'list2':list2,'list3':list3,'customer':customer_info,'customer_name':firstname})
            if lastname == None:
                # ---------------------sign up--------------------#
                c.close()
                connect = sql.create_cursor()
                email = request.POST['email']
                password = request.POST['password']
                password = get_hashed_value(password)
                print(email, password)
                to_execute = "Select * From CUSTOMER Where EMAIL = {email} " \
                            "and PASSWORD_HASH = {password}"
                to_execute = to_execute.format(
                    email=wrap_with_in_single_quote(email),
                    password=wrap_with_in_single_quote(password)
                )
                connect.execute(to_execute)
                customer = connect.fetchone()
                connect.close()
                print(customer)
                #customer = list(customer)
                print(customer)


homeApp/templates/homeApp/confirm_foodman.html
{% load static %}
{% static 'img' as baseURL %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>KHANABAZAAR/{{title}}</title>
     <!-- Required meta tags always come first -->
     <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
     <meta http-equiv="x-ua-compatible" content="ie=edge">
     <link rel="icon" type="image/png" href="{% static 'homeApp/img/khanabazaar.png' %}">
     
     <!--build:css css/main.css-->
     <link rel="stylesheet" href="{% static 'homeApp/modules/font-awesome/css/font-awesome.min.css' %}">
     <link rel="stylesheet" href="{% static 'homeApp/modules/bootstrap-social/bootstrap-social.css' %}">
     <!-- Bootstrap CSS -->
     <link rel="stylesheet" href="{% static 'homeApp/modules/bootstrap/dist/css/bootstrap.min.css' %}">
     <link rel="stylesheet" href="{% static 'homeApp/css/confirm_foodman.css' %}">
     <link rel="stylesheet" href="{% static 'homeApp/css/styles.css' %}">
     <!--flickity-->
     <link rel="stylesheet" href="https://unpkg.com/flickity@2/dist/flickity.min.css">
     <!--<script src="{% static 'homeApp/js/scripts.js' %}" async></script>-->
     <script src="{% static 'homeApp/js/confirm_foodman.js' %}" type="module" async></script>
     <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
          integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
          crossorigin=""/>
    <!-- Make sure you put this AFTER Leaflet's CSS -->
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
            integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
            crossorigin=""></script>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.2.0/dist/leaflet.css" />
    <link rel="stylesheet" href="https://unpkg.com/leaflet-routing-machine@latest/dist/leaflet-routing-machine.css" />
    <script src="https://unpkg.com/leaflet@1.2.0/dist/leaflet.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://unpkg.com/leaflet-routing-machine@latest/dist/leaflet-routing-machine.js"></script>
    <script type="text/javascript" src="{% static 'homeApp/js/haversine.js' %}"></script>
     <!--endbuild-->
</head>

<body data-spy="scroll" >
    <!--stylish box -->
    <div class="container">
        <div class="row row-content">
            <div class="box">
                <div class="content">
                    <h1>Thanks for the Order</h1>
                    <i class="fa fa-check-circle fa-5x tick" aria-hidden="true"></i>
                    <h2 class="status">PENDING!Please wait for a moment!! </h2>
                    <a href="{% url 'homeApp:homepage' %}" class="redirect btn btn-danger" id="redirect" role="button" class="btn">Go back to homepage</a>
                    
                    <h2 class="place-name"></h2>
                    <h2 class="place-distance"></h2>
                </div>

            </div>
        </div>
        <div class="row row-content">
            <div class="col-12 col-sm-6 container2">
                <div class="box2">
                    <div class="imgbox">
                        <img src="{% static 'homeApp/img/phone2.jpg' %}">
                    </div>
                    <div class="content">
                        <div class="icon">
                            <img src="{% static 'homeApp/img/phone.png' %}">
                        </div>
                        <h2 class="foodman-status" style="margin-left: -4px;">FOODMAN WILL BE AVAILABLE SOON</h2>
                        <img class="img-fluid rounded foodman-image" style="height: 200px;width:280px;"  src="{{ baseURL }}/{{ foodman.image }}" class="img-fluid" alt="Foodman not found">
                        <h3 class="foodman-contact"></h3>

                    </div>

                </div>
            </div>
            <div class="col-12 col-sm-6 container2">

                <div class="box2">
                    <div class="imgbox">
                        <img src="{% static 'homeApp/img/location4.jpg' %}" style="height: 650;width:600;">
                    </div>
                    <div class="content">
                        <div class="border-dark location-map" id="map" style="height: 520px; width: 100%;color:black"></div>
                        <h3 class="location-summary" style="display: none;">FOODMAN LOCATION NOT FOUND YET</h3>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <!--end of stylish box-->
    <!--<div class="box">
        <div class="form">
            <h1>Thanks for the Order</h1>
            <i class="fa fa-check-circle fa-5x tick" aria-hidden="true"></i>
            <h2>Estimated Delivery time:Within 2 hours</h2>
            <a href="{% url 'homeApp:homepage' %}" role="button" class="btn">Go back to homepage</a>
            <h2>{{foodman.name}}</h2>
            <div class="border-dark" id="map" style="height: 520px; width: 500px;color:black"></div>
        </div>
    
    </div>-->
    <!--login popup-->
    <!--<div class="login-popup bg">
        <div class="box">
             <div class="img-area">
                 <div class="img">
                 </div>
                 -<h1>Your Logo</h1>
             </div>
             <div class="form">
                 <h1>Thanks for the Order</h1>
                 <i class="fa fa-check-circle fa-5x tick" aria-hidden="true"></i>
                 <h2>Estimated Delivery time:Within 2 hours</h2>
                 <a href="{% url 'homeApp:homepage' %}" role="button" class="btn">Go back to homepage</a>
                 <h2>{{foodman.name}}</h2>
                 <div class="border-dark" id="map" style="height: 520px; width: 100%;color:black"></div>
             </div>
        </div>
   </div>-->
   <form action="{% url 'homeApp:confirm_foodman' %}" method="POST" style="overflow: auto;max-height:560px" hidden>
    {% csrf_token %}
        <input name="location" id="location" value="20,65" hidden>
        <input name="order_id" id="order_id" value={{order_id}} hidden>
        <input name="verify" id="verify" value={{verify}} hidden>
        <input name="foodman_name" id="foodman_name" value={{foodman.name}} hidden>
        <input name="foodman_location" id="foodman_location" value={{foodman.foodman_location}} hidden>
        <input name="foodman_location2" id="foodman_location2" value={{foodman.foodman_location}} hidden>
        <input name="foodman_phn" id="foodman_phn" value={{foodman.foodman_phone}} hidden>
        <input name="foodman_status" id="foodman_status" value={{foodman.status}} hidden>
        <input name="distance" id="distance" hidden>
        <input name="vehicle" id="vehicle" value="{{foodman.vehicleType}}" hidden>
        <button type="submit" id="submit_pop" class="btn" hidden>Confirm Checkout & Continue</button>


    </form>
   
   
   
    <!--end of login popup-->
    <!--end of login popup--> 
        

        

        <!--end of cart overlay-->
<!-- jQuery first, then Popper.js, then Bootstrap JS. -->
     <!--build:js js/main.js-->
     <script src="{% static 'homeApp/modules/jquery/dist/jquery.slim.min.js' %}"></script>
     <script src="{% static 'homeApp/modules/popper.js/dist/umd/popper.min.js' %}"></script>
     <script src="{% static 'homeApp/modules/bootstrap/dist/js/bootstrap.min.js' %}"></script>
     <script src="https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js"></script>
     <script type="text/javascript" src="{% static 'homeApp/js/haversine.js' %}"></script>
     <!--endbuild-->
</body>
</html>

homeApp/templates/homeApp/confirm_payment.html
{% load static %}
{% static 'img' as baseURL %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>KHANABAZAAR/{{title}}</title>
     <!-- Required meta tags always come first -->
     <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
     <meta http-equiv="x-ua-compatible" content="ie=edge">
     <link rel="icon" type="image/png" href="{% static 'homeApp/img/khanabazaar.png' %}">
     
     <!--build:css css/main.css-->
     <link rel="stylesheet" href="{% static 'homeApp/modules/font-awesome/css/font-awesome.min.css' %}">
     <link rel="stylesheet" href="{% static 'homeApp/modules/bootstrap-social/bootstrap-social.css' %}">
     <!-- Bootstrap CSS -->
     <link rel="stylesheet" href="{% static 'homeApp/modules/bootstrap/dist/css/bootstrap.min.css' %}">
     <link rel="stylesheet" href="{% static 'homeApp/css/confirm_pay.css' %}">
     <link rel="stylesheet" href="{% static 'homeApp/css/styles.css' %}">
     <link rel="stylesheet" href="{% static 'homeApp/css/login_popup_pay.css' %}">
     <!--flickity-->
     <link rel="stylesheet" href="https://unpkg.com/flickity@2/dist/flickity.min.css">
     <!--<script src="{% static 'homeApp/js/scripts.js' %}" async></script>-->
     <script src="{% static 'homeApp/js/confirm_pay.js' %}" type="module" async></script>
     <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
          integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
          crossorigin=""/>
    <!-- Make sure you put this AFTER Leaflet's CSS -->
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
            integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
            crossorigin=""></script>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.2.0/dist/leaflet.css" />
    <link rel="stylesheet" href="https://unpkg.com/leaflet-routing-machine@latest/dist/leaflet-routing-machine.css" />
    <script src="https://unpkg.com/leaflet@1.2.0/dist/leaflet.js"></script>
    <script src="https://unpkg.com/leaflet-routing-machine@latest/dist/leaflet-routing-machine.js"></script>
    <script type="text/javascript" src="{% static 'homeApp/js/haversine.js' %}"></script>
     <!--endbuild-->
</head>

<body data-spy="scroll" >
    <!--stylish box -->
    <div class="container">
        <div class="row row-content">
            <div class="box">
                <div class="content">
                    <h1>Thanks for the Order</h1>
                    <i class="fa fa-check-circle fa-5x tick" aria-hidden="true"></i>
                    <h2>Estimated Delivery time:Within 2 hours</h2>
                    <a href="{% url 'homeApp:homepage' %}" class="redirect" role="button" class="btn">Go back to homepage</a>
                    <h2>{{foodman.name}}</h2>
                </div>

            </div>
        </div>
        <div class="row row-content">
            <div class="col-12 col-sm-6 container2">
                <div class="box2">
                    <div class="imgbox">
                        <img src="{% static 'homeApp/img/promo.jpg' %}">
                    </div>
                    <div class="content">
                        <div class="icon">
                            <img src="{% static 'homeApp/img/promo.jpg' %}">
                        </div>
                        <h2>Your Available PROMOS</h2>
                    </div>

                </div>
            </div>
            <div class="col-12 col-sm-6 container2">

                <div class="box2">
                    <div class="imgbox">
                        <img src="{% static 'homeApp/img/location2.jpg' %}" style="height: 300;width:300;">
                    </div>
                    <div class="content">
                        <div class="border-dark" id="map" style="height: 520px; width: 100%;color:black"></div>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <!--end of stylish box-->
    <!--<div class="box">
        <div class="form">
            <h1>Thanks for the Order</h1>
            <i class="fa fa-check-circle fa-5x tick" aria-hidden="true"></i>
            <h2>Estimated Delivery time:Within 2 hours</h2>
            <a href="{% url 'homeApp:homepage' %}" role="button" class="btn">Go back to homepage</a>
            <h2>{{foodman.name}}</h2>
            <div class="border-dark" id="map" style="height: 520px; width: 500px;color:black"></div>
        </div>
    
    </div>-->
    <!--login popup-->
    <div class="login-popup">
        <div class="box3">
             <div class="form">
                 <form action="{% url 'homeApp:confirm_foodman' %}" method="POST" style="overflow: auto;max-height:560px">
                     {% csrf_token %}
                     <h3 style="font-weight: 600;margin-left:58px;font-family:Georgia, 'Times New Roman', Times, serif;color:black">Your Order is PENDING</h3>
                    <button type="submit" id="submit_pop" class="btn">Click here to wait & Proceed</button>
                    <input name="location" id="location" value="20,65" hidden>
                    <input name="order_id" id="order_id" value={{order_id}} hidden>
                 </form>
             </div>
        </div>
   </div>
    <!--end of login popup-->
    <!--end of login popup--> 
        

        

        <!--end of cart overlay-->
<!-- jQuery first, then Popper.js, then Bootstrap JS. -->
     <!--build:js js/main.js-->
     <script src="{% static 'homeApp/modules/jquery/dist/jquery.slim.min.js' %}"></script>
     <script src="{% static 'homeApp/modules/popper.js/dist/umd/popper.min.js' %}"></script>
     <script src="{% static 'homeApp/modules/bootstrap/dist/js/bootstrap.min.js' %}"></script>
     <script src="https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js"></script>
     <!--endbuild-->
</body>
</html>