foodmanApp/urls.py
from django.urls import path

app_name = 'foodmanApp'
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('current_order/', views.current_order, name='current_order'),
    path('accept_order/', views.accept_order, name='accept_order'),
    path('add_phone/', views.add_phone, name = 'add_phone'),
]

homeApp/urls.py
from django.urls import path

###registering appname to hyperlink in htmls
app_name = 'homeApp'
from . import views




urlpatterns = [
    path('',views.index,name="index"),
    path("aboutus",views.aboutus,name="aboutus"),
    path("contactus",views.contactus,name="contactus"),
    path("restaurant",views.restaurant,name="restaurant"),
    path("payment",views.payment,name="payment"),
    path("homepage",views.homepage,name="homepage"),
    path("restaurant_log_in",views.restaurant,name="restaurant_log_in"),
    path("confirm_payment",views.confirm_payment,name="confirm_payment"),
    path("confirm_foodman",views.confirm_foodman,name="confirm_foodman")


    
]

khanabazaar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin/', include("adminApp.urls")),
    path('', include("homeApp.urls")),
    path('rest/', include("restApp.urls")),
    path('foodman/', include("foodmanApp.urls")),
]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

foodmanApp/models.py
from django.db import models

# Create your models here.

foodmanApp/views.py
from django.contrib import messages
from django.shortcuts import render, redirect

from helper.fetch_all import currently_available_orders

app_name = 'foodmanApp'
# Create your views here.
from helper import session, sql, fetch_all
from helper.wrap_and_encode import wrap_with_in_single_quote, get_hashed_value


def index(request):
    context = {}
    session.not_this_season(request, app_name)
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        if email != '' and password != '':
            try:
                password = get_hashed_value(password)
                cursor = sql.create_cursor()
                to_execute = "SELECT * FROM FOODMAN WHERE EMAIL = {email} AND PASSWORD_HASH = {password}"
                to_execute = to_execute.format(
                    email=wrap_with_in_single_quote(email),
                    password=wrap_with_in_single_quote(password)
                )
                cursor.execute(to_execute)
                row = cursor.fetchone()
                if row is None:
                    messages.info(request, "Incorrect credintials")
                    return render(request, 'foodmanApp/sign_in.html', context)
                else:
                    request.session['app_name'] = app_name
                    request.session['id'] = row[0]
                    request.session['name'] = row[1]

                    request.session['location'] = row[6]
                    request.session['image_path'] = row[5]
                    request.session['status'] = row[7]
                    context.update(request.session)
                    # print(context)
                    return render(request, 'foodmanApp/index.html', context)
            except Exception as e:
                print(e)
                messages.info(request, 'Some error occured!!! please Try again!!!')
                return render(request, 'foodmanApp/sign_in.html', context)
                pass
            finally:
                cursor.close()
        else:
            messages.info(request, "Incorrect credintials")
            return render(request, 'foodmanApp/sign_in.html', context)

    elif request.method == 'GET':
        action = request.GET.get('action')
        if action == 'logout' and request.session['app_name'] == app_name:
            request.session.flush()
            print('log out ing')
            return render(request, 'foodmanApp/sign_in.html', context)
        if 'status' in request.GET:
            try:
                foodman_id = request.session.get('id')
                status = request.GET.get('status')
                cursor = sql.create_cursor()
                if status != request.session.get('status'):
                    request.session['status'] = status

                    cursor.callproc('CHANGE_FOODMAN_STATUS', [foodman_id, status])
                    print('succesfully changed status')
            except Exception as e:
                print('something is problem in status updation')
                print(e)
                pass
            finally:
                cursor.close()
        if 'location' in request.GET:
            try:
                foodman_id = request.session.get('id')
                location = request.GET.get('location')
                if location != request.session.get('location'):
                    request.session['location'] = location
                    to_execute = "UPDATE FOODMAN SET LOCATION = {location} WHERE ID = {id}"
                    to_execute = to_execute.format(
                        location=wrap_with_in_single_quote(location),
                        id=wrap_with_in_single_quote(foodman_id)
                    )
                    sql.execute(to_execute)
                    print(to_execute)
            except Exception as e:
                print(e)
                pass
        else:
            # print('why location is not being updated')
            pass

        if not request.session.is_empty():
            context.update(request.session)
            print(context)
            return render(request, 'foodmanApp/index.html', context)
        else:
            return render(request, 'foodmanApp/sign_in.html', context)

    # return render(request, 'foodmanApp/sign_in.html', context)


def current_order(request):
    context = {}
    if session.not_this_season(request, app_name):
        messages.info(request, 'Please Sign in first')
        return redirect('/foodman')
    foodman_id = request.session.get('id')
    status = request.session.get('status')
    if status == 'I' or status == 'F':
        messages.info(request, 'Please pick a order first')
        return redirect('/foodman')
    if request.method == 'GET':
        if 'status' in request.GET:
            try:
                foodman_id = request.session.get('id')
                status = request.GET.get('status')
                cursor = sql.create_cursor()
                if status != request.session.get('status'):
                    request.session['status'] = status

                    cursor.callproc('CHANGE_FOODMAN_STATUS', [foodman_id, status])
                    if status == 'F':
                        order_id = fetch_all.current_order_by_foodman(foodman_id)['id']
                        print(order_id)
                        cursor.callproc('ORDER_DELIVERED', [order_id])
                        messages.info(request, 'You have succefully completed the order!!!')
                        return redirect('/foodman')

                    print('succesfully changed status')
            except Exception as e:
                print('something is problem in status updation')
                print(e)
                pass
            finally:
                cursor.close()

        if 'location' in request.GET:
            try:
                foodman_id = request.session.get('id')
                location = request.GET.get('location')
                if location != request.session.get('location'):
                    request.session['location'] = location
                    to_execute = "UPDATE FOODMAN SET LOCATION = {location} WHERE ID = {id}"
                    to_execute = to_execute.format(
                        location=wrap_with_in_single_quote(location),
                        id=wrap_with_in_single_quote(foodman_id)
                    )
                    sql.execute(to_execute)
                    print(to_execute)
            except Exception as e:
                print(e)
                pass
        else:
            print('why location is not being updated')
    context.update(request.session)
    try:
        context['vehicle'] = fetch_all.foodman_vehicle(foodman_id)
        context['order'] = fetch_all.current_order_by_foodman(foodman_id)
        order_id = context['order']['id']
        rest_id = fetch_all.restaurant_ID_by_order_ID(order_id)
        context['restaurant'] = fetch_all.restaurant(rest_id)
    except Exception as e:
        print(e)
        order_id = fetch_all.current_order_by_foodman(foodman_id)['id']
        print(order_id)
        cursor = sql.create_cursor()
        cursor.callproc('CHANGE_FOODMAN_STATUS', [foodman_id, 'F'])
        cursor.callproc('ORDER_DELIVERED', [order_id])
        messages.info(request, "some unknown error occured!!! the order is automaticlly delivered")
    finally:
        try:
            cursor.close()
        except:
            pass
    return render(request, 'foodmanApp/current_order.html', context)


def accept_order(request):
    context = {}
    if session.not_this_season(request, app_name):
        messages.info(request, 'Please Sign in first')
        return redirect('/foodman')
    print(request.session.get('status'), 'F')
    if request.session.get('status') != 'F':
        messages.info(request, 'You are either busy or In rest.')
        return redirect('/foodman')

    if request.method == 'POST':
        order_id = request.POST.get('order')
        if order_id != '':
            try:
                foodman_id = request.session.get('id')

                cursor = sql.create_cursor()
                cursor.callproc('ORDER_PICKED', [order_id, foodman_id])
                print('Successfull')
                request.session['status'] = 'R'
                messages.info(request, 'order was successfully picked')
                return redirect('/foodman')
            except Exception as e:
                messages.info(request, 'some error happened')
                print('the order was already picked')
                print(e)
                pass
            finally:
                cursor.close()
        print(order_id)
        messages.info(request, 'Now delivery is our motto!!!!')

    context.update(request.session)
    context['orders'] = currently_available_orders()
    print(currently_available_orders())
    return render(request, 'foodmanApp/accept_order.html', context)


def add_phone(request):
    context = {}
    if session.not_this_season(request, app_name):
        messages.info(request, 'Please Sign in first')
        return redirect('/foodman')
    foodman_id = request.session.get('id')
    if request.method == 'POST':
        try:
            phone_no = request.POST.get('phone_no')
            cursor = sql.create_cursor()
            cursor.callproc('FOODMAN_ADD_PHONE_NO', [foodman_id, phone_no])
            messages.info(request, 'successfully updated phone no ')
        except Exception as e:
            print(e)
            messages.info(request, "some error occurred")
        finally:
            try:
                cursor.close()
            except:
                pass

        pass
    context = fetch_all.foodman(foodman_id)
    return render(request, 'foodmanApp/add_phone.html', context)

foodmanApp/templates/foodmanApp/accept_order.html
{% load static %}
{% static 'img' as baseURL %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>KHANABAZAAR foodman</title>
    <!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <link rel="icon" type="image/png" href="{% static 'foodmanApp/img/khanabazaar.png' %}">

    <!--build:css css/main.css-->
    <link rel="stylesheet" href="{% static 'foodmanApp/modules/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'foodmanApp/modules/bootstrap-social/bootstrap-social.css' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'foodmanApp/modules/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'foodmanApp/css/styles.css' %}">
    <!--flickity-->
    <link rel="text/stylesheet" href="https://unpkg.com/flickity@2/dist/flickity.min.css">
    <!--endbuild-->
</head>

<body class="background" data-spy="scroll">
<nav class="navbar navbar-dark bg-dark navbar-expand-sm fixed-top">
    <div class="container">
        <!--responsive navbar-->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'foodmanApp:index' %}"><img
                src="{% static 'foodmanApp/img/khanabazaar.png' %}"
                alt="LOGO" width="41" height="30">
            <span>KHANABAZAAR</span></a>
        <div class="collapse navbar-collapse" id="navbar">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active" hidden><a class="nav-link" href="#"><span class="fa fa-home fa-lg"></span>
                    Home</a>
                </li>
                <li class="nav-item" hidden><a class="nav-link" href="#"><span class="fa fa-info fa-lg"></span> AboutUs</a>
                </li>
                <li class="nav-item" hidden><a class="nav-link" href="#"><span class="fa fa-list fa-lg"></span> Menu</a>
                </li>
                <li class="nav-item" hidden><a class="nav-link" href="#"><span class="fa fa-address-card fa-lg"></span>
                    Contact</a>
                </li>

                {#                    <li class="nav-item"><a class="nav-link" role="button" id="login"><span class="fa fa-sign-in"></span> Sign In</a></li>#}
                <li class="nav-item"><a class="nav-link" id="user_name"><img class="img-fluid rounded
" style="height: 25px" src="{{ baseURL }}/{{ image_path }}"
                                                                             class="img-fluid"> {{ name }}</a>
                </li>

                <li class="nav-item"><a class="nav-link" role="button" id="logout" type="submit"
                                        href="{% url 'foodmanApp:index' %}?action=logout"><span
                        class="fa fa-sign-out"></span> Log out </a></li>

            </ul>
            <!--modal button-->
        </div>


    </div>

</nav>


<header class="jumbotron">
    <div class="container header-content">
        <div class="row">
            <div class="col-12 col-sm-6">
                <div class="title">
                    <h1 class="ml-0">🅺🅷🅰🅽🅰🅱🅰🆉🅰🅰🆁</h1>
                </div>
                <p>We take inspiration from the World's best cuisines, and create a unique fusion experience. Our
                    lipsmacking creations will tickle your culinary senses!</p>
            </div>
            <div class="col-12 col-sm-3 mt-0">
                <img src="{% static 'foodmanApp/img/khanabazaar.png' %}" class="img-fluid">
            </div>
            <div class="col-12 col-sm-3 align-self-center">
                <!--adding tooltip
                <a class="btn btn-block btn-warning btn-sm" href="#reservation" role="button"
                data-toggle="tooltip" data-html="true"
                title="or call at<br> +01710100921" data-placement="bottom">Reserve Table</a>-->
                <!--<a class="btn btn-block btn-warning btn-sm" href="#reservation" role="button" id="reservetable" >Reserve Table</a>-->


            </div>
        </div>
    </div>
</header>

<div class="container background">
    <h1 class="d-flex justify-content-center">Accept Order</h1>
    <div class="container">
        <form action="." method="POST" class="offset-1">
            {% csrf_token %}


            <div class="row form-group">
                <table class="table table-striped table-bordered  table-sm table-active table-hover"
                       id="order_table">
                    <thead class="thead-dark">
                    <tr>
                        <th scope="col">Order ID</th>

                        <th scope="col">Location</th>

                    </tr>
                    </thead>
                    <tbody>
                    {% for order in orders %}

                        <tr class="" id="order{{ forloop.counter }}" name="{{ order.id }}" scope="row"
                            value="">
                            <td>{{ order.id }}</td>
                            <td>{{ order.location }}</td>


                        </tr>

                    {% endfor %}
                    </tbody>

                </table>


            </div>


            <input class="d-none" id="order" name="order" value="">
            <div class="form-group row">
                <div class="offset-md-2 col-md-10">
                    <input type="submit" class="btn btn-primary" placeholder="submit" id="submit">

                </div>
            </div>

        </form>
        <script>
            document.addEventListener('DOMContentLoaded', function () {


                const submit = document.getElementById('submit');


                const order_num = {{ orders|length }};
                var selected_order = undefined;
                var i;


                // assigning order
                for (i = 1; i <= order_num; i++) {
                    var cell = document.getElementById('order' + i);
                    //console.log(cell.attributes.name.value);
                    cell.addEventListener('click', function (e) {

                        if (selected_order !== undefined) {
                            selected_order.attributes.class.value = "";
                            selected_order.attributes.value.value = "";
                        }

                        this.attributes.class.value = "bg-success";
                        this.attributes.value.value = name;
                        selected_order = this;

                    });
                    //console.log(cell);
                }


                submit.addEventListener('click', function (e) {

                    var i;
                    if (selected_order != undefined)
                        document.getElementById('order').value = selected_order.attributes.name.value;


                });


            });

        </script>

    </div>
    <script>
        var m = '';
        {% for message in messages %}
            m = m + '{{ message }}';
        {% endfor %}
        if (m != '')
            alert(m);
    </script>

    <!--restaurant 1st row-->


    <footer class="footer">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-4 col-sm-2">
                    <h5>Links</h5>
                    <ul class="list-unstyled">
                        <li><a href="#">Home</a></li>
                        <li><a href="#">About</a></li>
                        <li><a href="#">Menu</a></li>
                        <li><a href="#">Contact</a></li>
                    </ul>
                </div>
                <div class="col-7 col-sm-5">
                    <h5>Our Address</h5>
                    <address>
                        BailyRoad,Shantinagar<br>
                        Dhaka-1200<br>
                        Bangladesh<br>
                        <i class="fa fa-phone fa-lg"></i> Tel.: +852 1234 5678<br>
                        <i class="fa fa-fax fa-lg"></i> Fax: +852 8765 4321<br>
                        <i class="fa fa-envelope fa-lg"></i> Email: <a
                            href="mailto:confusion@food.net">khanabazaar@food.net</a>
                    </address>
                </div>
                <!--col aligning vertically center-->
                <div class="col-12 col-sm-4 align-self-center">
                    <div>
                        <a class="btn btn-social-icon btn-google" href="http://google.com/+"><i
                                class="fa fa-google fa-lg"></i> Google+</a>
                        <a class="btn btn-social-icon btn-facebook" href="http://www.facebook.com/profile.php?id="><i
                                class="fa fa-facebook fa-lg"></i> Facebook</a>
                        <a class="btn btn-social-icon btn-linkedin" href="http://www.linkedin.com/in/"><i
                                class="fa fa-linkedin fa-lg"></i> LinkedIn</a>
                        <a class="btn btn-social-icon btn-twitter" href="http://twitter.com/"><i
                                class="fa fa-twitter fa-lg"></i> Twitter</a>
                        <a class="btn btn-social-icon btn-google" href="http://youtube.com/"><i
                                class="fa fa-youtube fa-lg"></i> YouTube</a>
                        <a class="btn btn-social-icon" href="mailto:"><i class="fa fa-envelope-o fa-lg"></i> Mail</a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-auto">
                    <p>© Copyright 2020 KHANABAZAAR</p>
                </div>
            </div>
        </div>
    </footer>
    <!-- jQuery first, then Popper.js, then Bootstrap JS. -->
    <!--build:js js/main.js-->
    <script src="{% static 'foodmanApp/modules/jquery/dist/jquery.slim.min.js' %}"></script>
    <script src="{% static 'foodmanApp/modules/popper.js/dist/umd/popper.min.js' %}"></script>
    <script src="{% static 'foodmanApp/modules/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    {#<script src="{% static 'foodmanApp/js/scripts.js' %}"></script>#}
    {#<script src="{% static 'foodmanApp/js/form.js' %}"></script>#}
    <script src="https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js"></script>
    <!--endbuild-->

    <!--tootip function
    <script>
       $(function () {
           $('[data-toggle="tooltip"]').tooltip()
         })
    </script>-->

</body>


</html>

foodmanApp/templates/foodmanApp/add_phone.html
{% load static %}
{% static 'img' as baseURL %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>KHANABAZAAR Foodman</title>
    <!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <link rel="icon" type="image/png" href="{% static 'foodmanApp/img/khanabazaar.png' %}">

    <!--build:css css/main.css-->
    <link rel="stylesheet" href="{% static 'foodmanApp/modules/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'foodmanApp/modules/bootstrap-social/bootstrap-social.css' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'foodmanApp/modules/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'foodmanApp/css/styles.css' %}">
    <!--flickity-->
    <link rel="stylesheet" href="https://unpkg.com/flickity@2/dist/flickity.min.css">
    <!--endbuild-->
</head>

<body class="background" data-spy="scroll">
<nav class="navbar navbar-dark bg-dark navbar-expand-sm fixed-top">
    <div class="container">
        <!--responsive navbar-->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'foodmanApp:index' %}"><img
                src="{% static 'foodmanApp/img/khanabazaar.png' %}"
                alt="LOGO" width="41" height="30">
            <span>KHANABAZAAR</span></a>
        <div class="collapse navbar-collapse" id="navbar">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active" hidden><a class="nav-link" href="#"><span class="fa fa-home fa-lg"></span>
                    Home</a>
                </li>
                <li class="nav-item" hidden><a class="nav-link" href="#"><span class="fa fa-info fa-lg"></span> AboutUs</a>
                </li>
                <li class="nav-item" hidden><a class="nav-link" href="#"><span class="fa fa-list fa-lg"></span> Menu</a>
                </li>
                <li class="nav-item" hidden><a class="nav-link" href="#"><span class="fa fa-address-card fa-lg"></span>
                    Contact</a>
                </li>
                <li class="nav-item" hidden><a class="nav-link" role="button" id="login"><span
                        class="fa fa-sign-in"></span>
                    Sign In</a></li>
                <li class="nav-item"><a class="nav-link" id="user_name"><img class="img-fluid rounded
" style="height: 25px" src="{{ baseURL }}/{{ image_path }}"
                                                                             class="img-fluid"> {{ name }}</a>
                </li>
            </ul>
            <!--modal button-->
        </div>


    </div>

</nav>


<header class="jumbotron">
    <div class="container header-content">
        <div class="row">
            <div class="col-12 col-sm-6">
                <div class="title">
                    <h1 class="ml-0">🅺🅷🅰🅽🅰🅱🅰🆉🅰🅰🆁</h1>
                </div>
                <p>We take inspiration from the World's best cuisines, and create a unique fusion experience. Our
                    lipsmacking creations will tickle your culinary senses!</p>
            </div>
            <div class="col-12 col-sm-3 mt-0">
                <img src="{% static 'foodmanApp/img/khanabazaar.png' %}" class="img-fluid">
            </div>
            <div class="col-12 col-sm-3 align-self-center">
                <!--adding tooltip
                <a class="btn btn-block btn-warning btn-sm" href="#reservation" role="button"
                data-toggle="tooltip" data-html="true"
                title="or call at<br> +01710100921" data-placement="bottom">Reserve Table</a>-->
                <!--<a class="btn btn-block btn-warning btn-sm" href="#reservation" role="button" id="reservetable" >Reserve Table</a>-->


            </div>
        </div>
    </div>
</header>

<div class="container background">
    <h1 class="d-flex justify-content-center">Add a New Phone number </h1>
    <h2 class="d-flex justify-content-center">Current Number : {{ phone_no }} </h2>
    <form action="." method="POST" class="offset-1" enctype="multipart/form-data">
        {% csrf_token %}


        <div class="row form-group">
            <label for="phone_no" class="col-md-2 col-form-label bg-info d-flex justify-content-center">Phone no
                : </label>
            <div>
                <input type="text" class="form-control" id="phone_no" name="phone_no" placeholder="010...">
            </div>
        </div>


        <div class="form-group row">
            <div class="offset-md-2 col-md-10">
                <input type="submit" class="btn btn-primary" placeholder="submit">

            </div>
        </div>


    </form>
    <script>
        var m = ''
        {% for message in messages %}
            m = m + '{{ message }}'
            //console.log(m);
        {% endfor %}
        //console.log(m);
        if (m != '')
            alert(m);
    </script>
</div>

<div class="row restaurant-search-row-header">

</div>
<!--restaurant 1st row-->


<footer class="footer">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-4 col-sm-2">
                <h5>Links</h5>
                <ul class="list-unstyled">
                    <li><a href="#">Home</a></li>
                    <li><a href="#">About</a></li>
                    <li><a href="#">Menu</a></li>
                    <li><a href="#">Contact</a></li>
                </ul>
            </div>
            <div class="col-7 col-sm-5">
                <h5>Our Address</h5>
                <address>
                    121, Clear Water Bay Road<br>
                    Clear Water Bay, Kowloon<br>
                    HONG KONG<br>
                    <i class="fa fa-phone fa-lg"></i> Tel.: +852 1234 5678<br>
                    <i class="fa fa-fax fa-lg"></i> Fax: +852 8765 4321<br>
                    <i class="fa fa-envelope fa-lg"></i> Email: <a
                        href="mailto:confusion@food.net">confusion@food.net</a>
                </address>
            </div>
            <!--col aligning vertically center-->
            <div class="col-12 col-sm-4 align-self-center">
                <div>
                    <a class="btn btn-social-icon btn-google" href="http://google.com/+"><i
                            class="fa fa-google fa-lg"></i> Google+</a>
                    <a class="btn btn-social-icon btn-facebook" href="http://www.facebook.com/profile.php?id="><i
                            class="fa fa-facebook fa-lg"></i> Facebook</a>
                    <a class="btn btn-social-icon btn-linkedin" href="http://www.linkedin.com/in/"><i
                            class="fa fa-linkedin fa-lg"></i> LinkedIn</a>
                    <a class="btn btn-social-icon btn-twitter" href="http://twitter.com/"><i
                            class="fa fa-twitter fa-lg"></i> Twitter</a>
                    <a class="btn btn-social-icon btn-google" href="http://youtube.com/"><i
                            class="fa fa-youtube fa-lg"></i> YouTube</a>
                    <a class="btn btn-social-icon" href="mailto:"><i class="fa fa-envelope-o fa-lg"></i> Mail</a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-auto">
                <p>© Copyright 2020 KHANABAZAAR</p>
            </div>
        </div>
    </div>
</footer>
<!-- jQuery first, then Popper.js, then Bootstrap JS. -->
<!--build:js js/main.js-->
<script src="{% static 'foodmanApp/modules/jquery/dist/jquery.slim.min.js' %}"></script>
<script src="{% static 'foodmanApp/modules/popper.js/dist/umd/popper.min.js' %}"></script>
<script src="{% static 'foodmanApp/modules/bootstrap/dist/js/bootstrap.min.js' %}"></script>
{#<script src="{% static 'foodmanApp/js/scripts.js' %}"></script>#}
{#<script src="{% static 'foodmanApp/js/form.js' %}"></script>#}
<script src="https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js"></script>
<!--endbuild-->

<!--tootip function
<script>
   $(function () {
       $('[data-toggle="tooltip"]').tooltip()
     })
</script>-->

</body>


</html>